# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        GC\UserBundle\Entity\User: plaintext
    
    role_hierarchy:
        ROLE_CLIENT:      ROLE_CLIENT
        ROLE_COMPTA:      ROLE_CLIENT
        ROLE_ADMIN:       [ROLE_CLIENT, ROLE_COMPTA]
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    GC\UserBundle\Entity\User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
                pattern:      ^/
                anonymous:    true
                provider:     main
                form_login:
                    login_path: login
                    check_path: login_check
                logout:
                    path:       logout
                    target:     /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }