<?php

namespace GC\FactureBundle\Repository;

/**
 * Clients2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Clients2Repository extends \Doctrine\ORM\EntityRepository
{
}
